"""auto

Revision ID: 7cb90def3a6f
Revises: e53bc182edd6
Create Date: 2025-11-27 11:01:23.462682

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7cb90def3a6f"
down_revision: str | Sequence[str] | None = "e53bc182edd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("TRIGGER_FLIP_FLOW", name="actiontype").create(op.get_bind())
    op.create_table(
        "actions",
        sa.Column("tenant", sa.String(), nullable=False),
        sa.Column("trigger_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_type", postgresql.ENUM("TRIGGER_FLIP_FLOW", name="actiontype", create_type=False), nullable=False),
        sa.Column("action_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant", "trigger_id"], ["triggers.tenant", "triggers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("actions")
    sa.Enum("TRIGGER_FLIP_FLOW", name="actiontype").drop(op.get_bind())
    # ### end Alembic commands ###
