"""auto

Revision ID: e53bc182edd6
Revises:
Create Date: 2025-11-26 13:51:10.824542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e53bc182edd6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("ACTIVE", "INACTIVE", name="triggerstatus").create(op.get_bind())
    op.create_table(
        "triggers",
        sa.Column("tenant", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("ai_description", sa.String(length=1000), nullable=False),
        sa.Column("status", postgresql.ENUM("ACTIVE", "INACTIVE", name="triggerstatus", create_type=False), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("triggers")
    sa.Enum("ACTIVE", "INACTIVE", name="triggerstatus").drop(op.get_bind())
    # ### end Alembic commands ###
